version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/nextcloud"
  schedule:
    interval: weekly
- package-ecosystem: docker
  directory: "/nginx"
  schedule:
    interval: weekly
